[package]
name = "razer_rgb_mac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9"
eframe = "0.31"
egui = "0.31"
